name: CI/CD для Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout кода
        uses: actions/checkout@v2

      - name: Сборка Docker-образа
        run: docker build -t my-web-app .

      # Другие шаги CI/CD
